# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
hillary = Candidate.create(name: "Hillary Clinton",party: "Democrat")
lawrence = Candidate.create(name: "Lawrence Lessig",party: "Republican")
martin = Candidate.create(name: "Martin OMalley",party: "Democrat")
bernie = Candidate.create(name: "Bernie Sanders",party: "Democrat")
jimw  = Candidate.create(name: "Jim Webb",party: "Democrat")
jeb  = Candidate.create(name: "Jeb Bush",party: "Republican")
ben = Candidate.create(name: "Ben Carson",party: "Republican")
chris = Candidate.create(name: "Chris Christie",party: "Republican")
ted = Candidate.create(name: "Ted Cruz",party: "Republican")
carly = Candidate.create(name: "Carly Fiorina",party: "Republican")
jimg = Candidate.create(name: "Jim Gilmore",party: "Republican")
lindsey = Candidate.create(name: "Lindsey Graham",party: "Republican")
mike = Candidate.create(name: "Mike Huckabee",party: "Republican")
bobby = Candidate.create(name: "Bobby Jindal",party: "Republican")
john = Candidate.create(name: "John Kasich",party: "Republican")
george = Candidate.create(name: "George Pataki",party: "Republican")
rand = Candidate.create(name: "Rand Paul",party: "Republican")
marco = Candidate.create(name: "Marco Rubio",party: "Republican")
rick = Candidate.create(name: "Rick Santorum",party: "Republican")
donald = Candidate.create(name: "Donald Trump",party: "Republican")

 hc = Popcounter.create(candidate_id:  hillary.id)
 ll = Popcounter.create(candidate_id:  lawrence.id)
 mm = Popcounter.create(candidate_id:  martin.id)
 bs = Popcounter.create(candidate_id:  bernie.id)
 jw  = Popcounter.create(candidate_id: jimw.id)
 jb  = Popcounter.create(candidate_id: jeb.id)
 bc = Popcounter.create(candidate_id:  ben.id)
 cc = Popcounter.create(candidate_id:  chris.id)
 tc = Popcounter.create(candidate_id:  ted.id)
 cf = Popcounter.create(candidate_id:  carly.id)
 jg = Popcounter.create(candidate_id:  jimg.id)
 lg = Popcounter.create(candidate_id:  lindsey.id)
 mh = Popcounter.create(candidate_id:  mike.id)
 bj = Popcounter.create(candidate_id:  bobby.id)
 jk = Popcounter.create(candidate_id:  john.id)
  gp = Popcounter.create(candidate_id:  george.id)
 rp = Popcounter.create(candidate_id:  rand.id)
 mr = Popcounter.create(candidate_id:  marco.id)
 rs = Popcounter.create(candidate_id:  rick.id)
 dt = Popcounter.create(candidate_id:  donald.id)
